### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by ChrisDelClea** [TobiWeller/RDF2Vec-pytorch#1]
Hey @TobiWeller ,

is there any documentation or Python API i could use? 
Guess some examples would be super useful! 

Best regards
Chris

**Comment by TobiWeller** [comment]
Hey Chris,

there is one example in the main.py.
If you run the main.py file, then you should get the RDF2Vec embeddings using Skipgram on the MUTAG dataset. If you prefer CBOW, then comment line 114 and uncomment line 113 in the main.py. The classification uses a Support Vector Machine, as in the original paper (line 126).
The embeddings will be plotted using matplotlib (line 145 ff.).
If you want to save the embeddings uncomment line 117.

I hope this helps for the first steps. Otherwise feel free to write.


Cheers
Tobi

**Comment by ChrisDelClea** [comment]
Hi @TobiWeller,

thanks for that. Is there any way you could make this more generalizable aka. wrap it in a Python API and publish it on pypi? 

Best regards
Chris
